### ISSUE TITLE
Connecting Hoopla to an MCMC sampler

### ISSUE THREAD

**Issue by linan7788626** [linan7788626/LensWranglerPlusPlus#7]
### Goal

Connect Hoopla to emcee.js, allow a user to find a rough initial guess of a lens model based on the image of the input lensing system, then apply MCMC to improve the  accuracy of the guessed model.
### Tasks
- [ ] compute the difference between the "predicted image" and observed image.
- [ ] fit for the unknown noise level in the observed image.
- [ ] make the lens galaxies emit light and fit the light profile of the lens galaxies.
- [ ] Produce "cleaner" lensed images by subtracting the light profile of lenses and noise. 
- [ ] construct a "sample" button on the Hoopla page.

**Comment by drphilmarshall** [comment]
I think this might need the blue - red initialization referred to in #8 to happen first...

**Comment by linan7788626** [comment]
Yes, just added. #8 is sort of messy now. I will clean it up later. :-)
